#!/bin/bash

function repro.require_file {
    file=$1
    source=$2
    if [[ ! -f ${file} ]] ; then
        if [[ ${source} == http?:* ]] ; then
            wget --no-verbose -O ${file} ${source}/${file}
        else
            cp ${source}/${file} ${file}
        fi
    fi 
}

# 
repro_builder_release=${1:-https://raw.githubusercontent.com/repros-dev/repro-builder/master/.repro/exported}

# save the path to the original build directory
export REPRO_BOOTSTRAP_DIR=$(readlink -f $(dirname $0))

# work in the repro-builder subdirectory of the bootstrap directory
repro_builder_dir=${REPRO_BOOTSTRAP_DIR}/repro-builder
mkdir -p ${repro_builder_dir}
cd ${repro_builder_dir}

# install wget so that builders can be downloaded
apt-get -y update
apt-get -y install wget

# download the list of builders
build_manifest="manifest-build.txt"
repro.require_file ${build_manifest} ${repro_builder_release}

# process each line in the builders manifest
readarray lines < ${build_manifest}
for full_line in "${lines[@]}"
do
    # parse the builder name from the non-comment portion of the line
    trimmed_line=${full_line%%#*}
    read -ra tokens <<< ${trimmed_line}
    builder=${tokens[0]}
    repro.require_file ${builder} ${repro_builder_release}
done

# invoke each sequenced builder within the current shell
for builder in [0-9]*; do
    echo -e "STARTING  ${builder}"
    source $builder
done

