#!/bin/bash

function repro.require-file {
    file=$1
    source=$2
    if [[ ! -f ${file} ]] ; then
        if [[ ${source} == http?:* ]] ; then
            wget --no-verbose -O ${file} ${source}/${file}
        else
            cp ${source}/${file} ${file}
        fi
    fi 
}

# 
repros_builder_release=${1:-https://raw.githubusercontent.com/repros-dev/repros-builder/master/.repro/exported}

# save the path to the original build directory
export REPRO_BOOTSTRAP_DIR=$(readlink -f $(dirname $0))

# work in the repros-builder subdirectory of the bootstrap directory
repros_builder_dir=${REPRO_BOOTSTRAP_DIR}/repros-builder
mkdir -p ${repros_builder_dir}
cd ${repros_builder_dir}

# install wget so that builders can be downloaded
apt-get -y update
apt-get -y install wget

# download the list of builders
builders_manifest="manifest-builds.txt"
repro.require-file ${builders_manifest} ${repros_builder_release}

# process each line in the builders manifest
readarray lines < ${builders_manifest}
for full_line in "${lines[@]}"
do
    # parse the builder name from the non-comment portion of the line
    trimmed_line=${full_line%%#*}
    read -ra tokens <<< ${trimmed_line}
    builder=${tokens[0]}
    repro.require-file ${builder} ${repros_builder_release}
done

# invoke each sequenced builder within the current shell
for builder in [0-9]*; do
    echo -e "STARTING  ${builder}"
    source $builder
done

