#!/bin/bash

# work in directory containing this script
cd $(dirname $0)

# install wget so that builders can be downloaded
apt-get -y update
apt-get -y install wget

# download the builder script if necessary
if [[ ! -f build ]] ; then
    wget https://github.com/CIRSS/repro-builder/releases/download/v0.1.0/build
fi

# run the builder script
bash build
