#!/bin/bash

# set the URL of REPRO builder release to employ
export REPRO_BUILDER_RELEASE_URL=https://github.com/CIRSS/repro-builder/releases/download/v0.1.0

# save the path to the original build directory
export REPRO_BUILD_DIR=$(readlink -f $(dirname $0))

# work in the cache subdirectory of the build directory
cache_dir=${REPRO_BUILD_DIR}/cache
mkdir -p ${cache_dir}
cd ${cache_dir}

# install wget so that builders can be downloaded
apt-get -y update
apt-get -y install wget

if [[ ! -f builders.txt ]] ; then
    wget --quiet ${REPRO_BUILDER_RELEASE_URL}/builders.txt
fi

readarray lines < builders.txt

for full_line in "${lines[@]}"
do
    trimmed_line=${full_line%%#*}
    read -ra tokens <<< ${trimmed_line}
    artifact_name=${tokens[0]}
    if [[ ! -f ${artifact_name} ]] ; then
        wget -nv -O ${artifact_name} ${REPRO_BUILDER_RELEASE_URL}/${artifact_name}
    fi
done

for filename in [0-9]*; do
    echo -e "STARTING  ${filename}"
    source $filename
done

