#!/bin/bash

# set the URL of REPRO builder release to employ
export REPRO_BUILDER_RELEASE_URL=https://github.com/CIRSS/repro-builder/releases/download/v0.1.0

# save the path to the original build directory
export REPRO_BUILD_DIR=$(readlink -f $(dirname $0))

# work in the cache subdirectory of the build directory
cache_dir=${REPRO_BUILD_DIR}/cache
mkdir -p ${cache_dir}
cd ${cache_dir}

# install wget so that builders can be downloaded
apt-get -y update
apt-get -y install wget

# download the list of builders
if [[ ! -f builders.txt ]] ; then
    wget --quiet ${REPRO_BUILDER_RELEASE_URL}/builders.txt
fi

# process each line in the builders list
readarray lines < builders.txt
for full_line in "${lines[@]}"
do
    # parse the builder name from the non-comment portion of the line
    trimmed_line=${full_line%%#*}
    read -ra tokens <<< ${trimmed_line}
    builder=${tokens[0]}

    # download this builder if not already in the local cache
    if [[ ! -f ${builder} ]] ; then
        wget -nv -O ${builder} ${REPRO_BUILDER_RELEASE_URL}/${builder}
    fi
done

# invoke each sequenced builder within the current shell
for builder in [0-9]*; do
    echo -e "STARTING  ${builder}"
    source $builder
done

